### ISSUE TITLE
[Bug] fakeip 设置白名单模式无效

### ISSUE THREAD

**Issue by MaxMaoSu** [pompurin404/mihomo-party#175]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/docs/issues/common)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS, Windows

### 系统版本

windows 11 和 mac os 15

### 发生问题 mihomo-party 版本

latest

### 描述

  ```
enhanced-mode: fake-ip
  fake-ip-filter-mode: whitelist
  fake-ip-filter:
    - 'rule-set:personal-proxy'
    - 'rule-set:gfw'
```
注：目前最新内核已经支持fake-ip-filter配置 ruleset，故排除内核问题。

在mihomo party配置文件中fake ip模式已经设置为白名单，filter 写入 gfw 等常用代理规则，理论上来说规则之外的域名都会dns 解析为 real ip，但在连接记录中查看依然为 fakeip，希望作者可以检查一下程序代码，谢谢

### 重现方式

目前身边无设备，暂无法贴上 bug 贴图

**Comment by xishang0128** [comment]
@MaoSuSu 请确保不是自己使用方式导致的

**Comment by MaxMaoSu** [comment]
> @MaoSuSu 请确保不是自己使用方式导致的
```
port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: silent
external-controller: 127.0.0.1:9090
ipv6: true
tcp-concurrent: true
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

geox-url:
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country-lite.mmdb"
geo-auto-update: true
geo-update-interval: 168

sniffer:
  enable: false
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80]
    TLS:
      ports: [443]
    QUIC:
      ports: [443]
  skip-domain:
    - '+.apple.com'
    - Mijia Cloud
    - dlg.io.mi.com

dns:
  enable: true
  ipv6: true
  listen: :53
  nameserver:
    - system
  enhanced-mode: fake-ip
  fake-ip-filter-mode: whitelist
  fake-ip-filter:
    - 'rule-set:personal-proxy'
    - 'rule-set:gfw'
```

<img width="809" alt="image" src="https://github.com/user-attachments/assets/b3bbcb47-ec50-451e-8319-dc7aaf037351">

开启 tun 模式，关闭系统代理，关闭域名嗅探，连接中国内域名为 fakeip（哔哩哔哩）

**Comment by xishang0128** [comment]
@MaoSuSu 如何确定是fakeip?

**Comment by MaxMaoSu** [comment]
> @MaoSuSu 如何确定是fakeip?

<img width="783" alt="image" src="https://github.com/user-attachments/assets/adc76b1a-5e62-4f6d-9593-cef0c0572091">

**Comment by xishang0128** [comment]
@MaoSuSu 检查运行时配置

**Comment by MaxMaoSu** [comment]
> @MaoSuSu 检查运行时配置
运行时配置：
```
port: 7892
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
ipv6: true
tcp-concurrent: false
global-client-fingerprint: chrome
profile:
  store-selected: true
  store-fake-ip: true
geox-url:
  mmdb: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
  geoip: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  asn: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb
geo-auto-update: false
geo-update-interval: 24
sniffer:
  enable: false
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
        - 80
    TLS:
      ports:
        - 443
    QUIC:
      ports:
        - 443
  skip-domain:
    - +.apple.com
    - Mijia Cloud
    - dlg.io.mi.com
dns:
  enable: true
  ipv6: true
  listen: :53
  nameserver:
    - system
  enhanced-mode: fake-ip
  fake-ip-filter-mode: whitelist
  fake-ip-filter:
    - rule-set:personal-proxy
    - rule-set:gfw
proxies:
#已删除节点信息

proxy-groups:
  - name: 🔗 规则之外
    type: select
    proxies:
      - ☁️ 节点
      - DIRECT
rule-providers:
  private:
    type: http
    behavior: domain
    url: https://testingcf.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: ./ruleset/private.yaml
    interval: 86400
  personal-direct:
    type: http
    behavior: domain
    url: https://testingcf.jsdelivr.net/gh/MaoSuSu/clash-rules-personal@main/direct.yaml
    path: ./ruleset/personal-direct.yaml
    interval: 86400
  ad:
    type: http
    behavior: domain
    url: https://testingcf.jsdelivr.net/gh/TG-Twilight/AWAvenue-Ads-Rule@main/Filters/AWAvenue-Ads-Rule-Clash.yaml
    path: ./ruleset/ad.yaml
    interval: 86400
  personal-proxy:
    type: http
    behavior: domain
    url: https://testingcf.jsdelivr.net/gh/MaoSuSu/clash-rules-personal@main/proxy.yaml
    path: ./ruleset/personal-proxy.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: https://testingcf.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
    path: ./ruleset/gfw.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: https://testingcf.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
rules:
  - AND,((NETWORK,udp),(DST-PORT,443)),REJECT-DROP
  - RULE-SET,private,DIRECT
  - RULE-SET,ad,REJECT-DROP
  - RULE-SET,personal-proxy,☁️ 节点
  - RULE-SET,personal-direct,DIRECT
  - RULE-SET,gfw,☁️ 节点
  - RULE-SET,telegramcidr,☁️ 节点
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,🔗 规则之外
secret: ""
mixed-port: 7890
redir-port: 0
tproxy-port: 0
unified-delay: false
find-process-mode: strict
bind-address: "*"
lan-allowed-ips:
  - 0.0.0.0/0
  - ::/0
lan-disallowed-ips: []
authentication: []
skip-auth-prefixes:
  - 127.0.0.1/32
tun:
  enable: false
  stack: system
  auto-route: true
  auto-redirect: false
  auto-detect-interface: true
  dns-hijack:
    - any:53
  mtu: 1500
  strict-route: false
geodata-mode: true
```
