### ISSUE TITLE
[Feature] 增加功能使能在 Windows 10/11 开启 Tun 时设置其他网卡接口 DNS 地址为内核 DNS 模块监听地址

### ISSUE THREAD

**Issue by silver716** [pompurin404/mihomo-party#229]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

## 环境

操作系统：Windows 11 x64

软件版本：Mihomo Party v1.4.3

内核版本：alpha-9fd63fe

运行配置：

<details>
<summary>TUN 模块</summary>

```yaml
tun:
  enable: false
  stack: system
  dns-hijack:
    - any:53
  auto-route: true
  device: Mihomo
  auto-redirect: false
  auto-detect-interface: true
  mtu: 1480
  strict-route: false
```

</details>

<details>
<summary>DNS 模块</summary>

```yaml
dns:
  cache-algorithm: arc
  enable: true
  listen: "[::0]:53"
  ipv6: true
  ipv6-timeout: 300
  default-nameserver:
    - system
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - rule-set:fake-ip-filter
  fake-ip-filter-mode: blacklist
  use-hosts: true
  respect-rules: false
  nameserver:
    - proxied_1
    - proxied_2
    - proxied_3
  proxy-server-nameserver:
    - system
  direct-nameserver:
    - system
  direct-nameserver-follow-policy: false
  nameserver-policy:
    geosite:cn,private,apple:
      - system
    geosite:category-ads-all: rcode://success
  use-system-hosts: true
  fallback: []
  fallback-filter: {}
```

</details>

### 智能多宿主解析的问题

Windows 的「Smart Multi-Homed Name Resolution」机制，会将待解析域名送至所有可用网卡接口尝试解析。这一过程会造成 DNS 泄露。

传统地，可使用组策略或注册表编辑器关闭这一功能。但这在 Windows 10/11 上并不那么有效，参考 https://medium.com/@ValdikSS/beware-of-windows-10-dns-resolver-and-dns-leaks-5bc5bfb4e3f1 。

实际测试发现，即使关闭了上述功能，在查询 AAAA 记录时，域名仍会被非预期 DNS 解析，而出现泄露。已有 issue 描述了此现象 https://github.com/MetaCubeX/mihomo/issues/854 。

### Strict Route 的问题

启用内核 Strict Route 可解决上述问题。

但 Strict Route 造成了新的问题：
- WSL 工作异常：https://web.archive.org/web/https://cyrus28214.top/post/b173a6854994/index.html
- https://github.com/MetaCubeX/mihomo/issues/778

一番研究后发现，不使用 Strict Route，而将网卡 DNS 地址改为内核 DNS 模块监听地址，可完美解决此问题。类似于 OpenVPN https://www.dnsleaktest.com/how-to-fix-a-dns-leak.html 。

Powershell 命令：
```ps1
Set-DnsClientServerAddress -InterfaceAlias "WiFi" -ServerAddresses ("127.0.0.1","::1")
```

恢复：
```ps1
Set-DnsClientServerAddress -InterfaceAlias "WiFi" -ResetServerAddresses
```

由于这一问题为 Windows 10/11 独有，此功能由 GUI 实现较合适。如能实现，将会便利很多，故有此 issue。
