### ISSUE TITLE
[Feature] 递归显示策略组延迟测试结果

### ISSUE THREAD

**Issue by posthumz** [pompurin404/mihomo-party#248]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [X] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [X] 这是向GUI程序提出的功能请求,而不是内核程序
- [X] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

例如对以下中的`Collection`进行测速，只能看见`group[AB]`的整体延迟测速结果，不能在`group[AB]`中显示`proxy[1234]`的结果。而且因为不显示结果不知道`fallback`和`url-test`代理组中当前自动选中的节点。
```
proxy-groups:

  - name: Collection
    type: fallback
    proxies: [groupA, groupB]

  - name: groupA
    type: fallback
    proxies: [proxy1, proxy2]

  - name: groupB
    type: url-test
    proxies: [proxy3, proxy4]
```
