### ISSUE TITLE
[Bug] 使用自定义Geoip和规则时内核无法成功加载

### ISSUE THREAD

**Issue by JxQg** [pompurin404/mihomo-party#277]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [x] 我未在 [Issue Tracker](./?q=is%3Aissue) 中找到我要提出的问题
- [x] 我未在 [常见问题](https://mihomo.party/docs/issues/common) 中找到我要提出的问题
- [X] 这是 GUI 程序的问题，而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 11 专业工作站版 版本号	23H2 安装日期	‎2023/‎5/‎8 操作系统版本	22631.4317 体验	Windows Feature Experience Pack 1000.22700.1041.0

### 发生问题 mihomo-party 版本

v.1.5.3

### 描述

无法正确加载配置文件中的Geoip的地区配置。

1. 加载订阅文件 
```
mixed-port: 7890
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
ipv6: false
find-process-mode: off
external-controller: 0.0.0.0:9090
secret: 123456
profile:
  store-selected: true
  store-fake-ip: false
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
geodata-mode: true
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat
  geosite: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb
  asn: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb
global-ua: clash.meta
etag-support: true
dns:
  enable: true
  prefer-h3: true
  ipv6: false
  enhanced-mode: redir-host
  use-hosts: true
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver-policy:
    geosite:cn,private,category-games@cn:
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    geosite:geolocation-!cn:
      - https://cloudflare-dns.com/dns-query#🎰 DNS出口
      - https://dns.google/dns-query#🎰 DNS出口
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "*"
    - +.lan
    - +.local
    - dlg.io.mi.com
    - +.apple.com
    - one.one.one.one
    - +.cloudflare-dns.com
    - dns.google
    - dot.pub
    - +.doh.pub
    - dns.alidns.com
proxies:
  - {name: 🇭🇰 香港-SDC }
  - {name: 🇭🇰 香港-SDC }
  - {name: 🇭🇰 香港-IDC }
  - {name: 🇺🇸 美国-洛杉矶 }
  - {name: 🇺🇸 美国-洛杉矶 }
  - {name: 🇸🇬 狮城-SDC }
  - {name: 🇨🇳 台湾-SDC }
  - {name: 🇯🇵 日本-大版 }
  - {name: 🇯🇵 日本-东京 }
proxy-groups:
*
rules:
  - DST-PORT,22/9993,DIRECT
  - SRC-PORT,22/9993,DIRECT
  - DOMAIN-SUFFIX,jxq.io,DIRECT
  - RULE-SET,jxgggg,🧱 JxQggg
  - GEOIP,private,📡 直连网络,no-resolve
  - GEOSITE,private,📡 直连网络
  - GEOSITE,category-ads-all,🛑 广告拦截
  - RULE-SET,Privacy,🛡️ 隐私防护
  - RULE-SET,IPTest,📟 IPInfo
  - RULE-SET,CDN,🆘 CDN服务
  - RULE-SET,EricPrivate,👨🏻‍🎤 Eric.Cus
  - RULE-SET,MovieDB,🎦 MovieDB
  - RULE-SET,OpenAI,🤖 OPENAI
  - RULE-SET,Microsoft,🪟 Microsoft
  - RULE-SET,Telegram,📠 Telegram
  - RULE-SET,Apple,🍎 Apple
  - RULE-SET,ChinaMedia,🎥 国内影音
  - GEOSITE,category-dev,🧰 开发网站
  - GEOSITE,google,🔎 Google
  - RULE-SET,Cloudflarecn,📡 直连网络
  - GEOSITE,category-dev-cn,📡 直连网络
  - GEOSITE,category-media-cn,📡 直连网络
  - GEOSITE,apple-cn,📡 直连网络
  - GEOSITE,tld-cn,📡 直连网络
  - GEOSITE,category-games@cn,📡 直连网络
  - GEOSITE,category-ntp-cn,📡 直连网络
  - GEOSITE,steam,🎮 Steam
  - GEOSITE,xbox,🎮 Xbox
  - GEOSITE,epicgames,🎮 Epic
  - GEOSITE,nintendo,🎮 Nintendo
  - GEOSITE,playstation,🎮 PlayStation
  - GEOSITE,category-cryptocurrency,🪙 Bitcoin
  - GEOSITE,youtube,📹 YouTube
  - GEOSITE,netflix,🎞️ Netflix
  - GEOSITE,tiktok,🎼 TikTok
  - RULE-SET,TikTok,🎼 TikTok
  - GEOSITE,bahamut,🎬 巴哈姆特
  - GEOSITE,bilibili@!cn,📺 哔哩海外
  - GEOSITE,category-entertainment,📽️ 国外影音
  - GEOSITE,category-social-media-!cn,💭 国外社交
  - GEOSITE,category-communication,💭 国外社交
  - RULE-SET,Speedtest,📶 SpeedTest
  - RULE-SET,PayPal,🎰 PayPal
  - RULE-SET,rule-provider,🚩 社交IP归属
  - GEOSITE,gfw,🚀 出口网络
  - GEOSITE,cn,📡 直连网络
  - GEOIP,cloudflare,🌫️ 边缘云,no-resolve
  - GEOIP,cloudfront,🌫️ 边缘云,no-resolve
  - GEOIP,google,🔎 Google,no-resolve
  - GEOIP,HK,🪷 香港-HK,no-resolve
  - GEOIP,US,🪦 美国-US,no-resolve
  - GEOIP,TW,🏝️ 台湾-TW,no-resolve
  - GEOIP,JP,🌸 日本-JP,no-resolve
  - GEOIP,SG,🦁 狮城-SG,no-resolve
  - GEOIP,CN,📡 直连网络,no-resolve
  - GEOSITE,geolocation-!cn,🌍 国外网址
  - MATCH,🐟 其他网络
rule-providers:
*
```
2. 修改Geoip和Geosite文件下载地址与配置文件中相同
<img width="734" alt="rouue3x5 4yp" src="https://github.com/user-attachments/assets/b9ddc3a2-9ef1-4538-b375-f7fb3544d8af">

3. 更新Geoip数据文件 
![PixPin_2024-10-24_09-05-39](https://github.com/user-attachments/assets/c6b99192-6593-4f29-8a3e-bc8c9a502579)

4. 内核启动报错 无法找到对应IP信息 
![PixPin_2024-10-24_09-11-57](https://github.com/user-attachments/assets/d4f09bdc-5125-4657-8296-3afb3a69a52a)

已确认Geoip包含了规则中所需要的内容，因为我在Clash-Verge和OpenClash使用相同的规则并且使用指定的Geo数据文件，可以正常执行。

### 重现方式

使用指定地区配置并更新任意自定义Geo数据。
