### ISSUE TITLE
[Feature] 增加虚拟网卡设置 route-exclude-address 配置选项

### ISSUE THREAD

**Issue by yyhhyyyyyy** [pompurin404/mihomo-party#318]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [x] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

希望在`虚拟网卡设置`页 加一个 route-exclude-address 的 文本框
或者在`应用设置`中加一个 接管Tunnel 设置的选项  

尝试使用覆写，但写完后，不生效，始终使用的是GUI面板中的`虚拟网卡设置`
希望增加，谢谢！

**Comment by ghost** [comment]
我测试覆写没有问题

![Image](https://github.com/user-attachments/assets/442fe1f8-d775-4781-8790-784afdccb8d2)

![Image](https://github.com/user-attachments/assets/fbee8024-94e4-4b56-b21c-3a45ab5c4783)

**Comment by yyhhyyyyyy** [comment]
我用js和yaml都有问题  觉得应该是我之前手动点过tunnel设置的`保存`按钮 导致这部分的覆写无效了

**覆写脚本**:
```js
function main (params) {
    overwriteTunnel(params);
    return params;
}
// 覆写Tunnel
function overwriteTunnel (params) {
    const tunnelOptions = {
        enable: true,
        stack: "system",
        device: "tun0",
        "dns-hijack": ["any:53", "tcp://any:53"],
        "auto-route": true,
        "auto-detect-interface": true,
        "strict-route": true,
        "route-exclude-address": ["172.20.0.0/16"],
    };
    params.tun = { ...tunnelOptions };
}
```

**当前运行时配置**：
```yaml
tun:
  enable: true
  stack: system
  device: Mihomo
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true
  strict-route: true
  route-exclude-address: []
  auto-redirect: false
  mtu: 1500
```
