### ISSUE TITLE
[Feature] 保留覆写配置文件中的 DNS 和嗅探设置不被 GUI 覆盖

### ISSUE THREAD

**Issue by gsuns** [pompurin404/mihomo-party#355]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [x] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

使用环境:
Mihomo只用作分流,代理走本地Socks5 1080端口.
我已经完整的配置了 入站 ;出站 ; DNS ; 分流规则 ; GEO.请看下面的配置.
```


# 开启 IPv6 总开关，关闭阻断所有 IPv6 链接和屏蔽 DNS 请求 AAAA 记录
ipv6: true

## 控制是否让 Clash 去匹配进程
# always 开启，强制匹配所有进程
# strict 默认，由 Clash 判断是否开启
# off 不匹配进程，推荐在路由器上使用此模式
find-process-mode: strict

tun:
  enable: true
  stack: system
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack:
    - udp:53
  device: utun0
  strict-route: true
  udp-timeout: 300
  iproute2-table-index: 2022
  iproute2-rule-index: 9000
  endpoint-independent-nat: false
  route-address:
    - 0.0.0.0/1
    - 128.0.0.0/1
    - "::/1"
    - "8000::/1"
  route-exclude-address:
  - 192.168.0.0/16
  - fc00::/7
  include-android-user:
  - 0

#出站
proxies:
  #Socks5
  - name: LocalSocks5
    type: socks5
    server: 127.0.0.1
    port: 1080

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - LocalSocks5

  # url-test 通过对 指定URL 进行基准速度测试来选择将使用哪个代理.
  - name: "Auto"
    type: url-test
    proxies:
      - LocalSocks5
    # tolerance: 150
    # lazy: true
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

# 嗅探域名 可选配置
sniffer:
  enable: true
  parse-pure-ip: true
  force-dns-mapping: true
  override-destination: true
  sniff:
    HTTP:
      ports:
        - 80
        - 443
      override-destination: true
    TLS:
      ports:
        - 443
    QUIC:
      ports:
        - 443
  skip-domain:
    - +.push.apple.com

# DNS 配置
dns:
  enable: true
  prefer-h3: true 
  listen: :53
  default-nameserver:
    - 223.5.5.5
  enhanced-mode: redir-host 
  fake-ip-range: 192.169.0.0/16 

  # 配置不使用 fake-ip 的域名
  fake-ip-filter:
    - geosite:CN

  fake-ip-filter-mode: blacklist
  use-hosts: false
  use-system-hosts: true
  respect-rules: false
  nameserver:
    - https://1.1.1.1/dns-query#Proxy
  fallback:
    - https://1.1.1.1/dns-query#Proxy
    - 
  proxy-server-nameserver:
    - https://1.1.1.1/dns-query#Proxy



  # 配置查询域名使用的 DNS 服务器
  nameserver-policy:
    +.nvidia.cn: rcode://success
    geosite:CN:
      - 223.5.5.5
      - 223.6.6.6
    geosite:category-ads-all: rcode://success
    +.baidu.com,+.google.cn:
      - 223.5.5.5
      - 223.6.6.6
    dns.origin.gdn:
      - 1.1.1.1#Proxy
      - 8.8.8.8#Proxy
      - 8.8.4.4#Proxy
    +.*:
    - https://1.1.1.1/dns-query#Proxy



rule-providers:
  Domain-CN:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs

rules:
  # 私有地址 - 直连
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT

  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,169.254.0.0/16,DIRECT
-   
  - GEOIP,CN,DIRECT

# IP代理
  - IP-CIDR,1.1.1.1/32,Proxy

  - AND,((NETWORK,UDP),(DST-PORT,53),(DOMAIN-SUFFIX,+.nvidia.cn)),REJECT

# 域名直连
  - DOMAIN-SUFFIX,cn,DIRECT


# 域名代理
  - DOMAIN-SUFFIX,google.com,Proxy


# 应用代理
  - PROCESS-NAME,qq.exe,DIRECT


  - MATCH,DIRECT

## 自动更新 GEO
geo-auto-update: true
geo-update-interval: 24
geodata-mode: false
geox-url:
  geoip: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
  asn: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb
```
他完全符合我使用习惯.
但问题在于
![Image](https://github.com/user-attachments/assets/e073c012-dedf-4edd-902e-f3c73f497dff)
无论我在覆写中导入这个配置并在订阅中导入这个配置.
DNS 和 嗅探 还有GEOIP,都是按照 GUI上的设置覆盖我的自定义配置
![Image](https://github.com/user-attachments/assets/83f21f68-0f30-46a3-911e-71c3f60c1d67)
![Image](https://github.com/user-attachments/assets/f7ca077b-9dd5-4a32-832c-220312cf9911)

希望可以解决
